package algorithms.mazeGenerators;

import java.io.Serializable;

/**
 * Represents a maze with a start and goal position.
 * Each cell in the maze can be either a wall (1) or a path (0).
 */
public class Maze implements Serializable {
    private int[][] maze;
    private int rows;
    private int columns;
    private Position startPosition;
    private Position goalPosition;

    /**
     * constructs a new Maze with specified dimensions.
     *
     * @param rows    Number of rows in the maze.
     * @param columns Number of columns in the maze.
     */
    public Maze(int rows, int columns) {

        if (rows<2 && columns<2){
            throw new IllegalArgumentException("Rows or columns number are not valid");
        }
        this.maze = new int[rows][columns];
        this.rows = rows;
        this.columns = columns;
    }
    /**
     * Constructs a Maze from a given byte array.
     * Expects the array to follow the format generated by toByteArray().
     */
    public Maze(byte[] byteArray) {
        if (byteArray == null || byteArray.length < 12)
            throw new IllegalArgumentException("Invalid byte array for maze reconstruction.");

        // Parse metadata from header (2 bytes per field, big-endian)
        this.rows = ((byteArray[0] & 0xFF) << 8) | (byteArray[1] & 0xFF);
        this.columns = ((byteArray[2] & 0xFF) << 8) | (byteArray[3] & 0xFF);
        int startRow = ((byteArray[4] & 0xFF) << 8) | (byteArray[5] & 0xFF);
        int startCol = ((byteArray[6] & 0xFF) << 8) | (byteArray[7] & 0xFF);
        int goalRow = ((byteArray[8] & 0xFF) << 8) | (byteArray[9] & 0xFF);
        int goalCol = ((byteArray[10] & 0xFF) << 8) | (byteArray[11] & 0xFF);

        // Set positions
        this.startPosition = new Position(startRow, startCol);
        this.goalPosition = new Position(goalRow, goalCol);

        // Parse maze body
        this.maze = new int[rows][columns];
        int index = 12;
        for (int i = 0; i < rows; i++) {
            for (int j = 0; j < columns; j++) {
                this.maze[i][j] = byteArray[index++];
            }
        }
    }


    /**
     * Converts the maze into a byte array including metadata (header + body).
     * Header format (12 bytes): rows, columns, startRow, startCol, goalRow, goalCol (2 bytes each).
     * Body: each cell as a byte (0 or 1).
     */
    public byte[] toByteArray() {
        byte[] byteArray = new byte[12 + (rows * columns)];

        // Store metadata: each value split into 2 bytes (big-endian)
        byteArray[0] = (byte) (rows >> 8);
        byteArray[1] = (byte) (rows);
        byteArray[2] = (byte) (columns >> 8);
        byteArray[3] = (byte) (columns);
        byteArray[4] = (byte) (startPosition.getRowIndex() >> 8);
        byteArray[5] = (byte) (startPosition.getRowIndex());
        byteArray[6] = (byte) (startPosition.getColumnIndex() >> 8);
        byteArray[7] = (byte) (startPosition.getColumnIndex());
        byteArray[8] = (byte) (goalPosition.getRowIndex() >> 8);
        byteArray[9] = (byte) (goalPosition.getRowIndex());
        byteArray[10] = (byte) (goalPosition.getColumnIndex() >> 8);
        byteArray[11] = (byte) (goalPosition.getColumnIndex());

        // Flatten the maze grid into the body of the array
        int index = 12;
        for (int i = 0; i < rows; i++) {
            for (int j = 0; j < columns; j++) {
                byteArray[index++] = (byte) maze[i][j];
            }
        }

        return byteArray;
    }


    /**
     * returns the internal 2D array representing the maze.
     *
     * @return A 2D array where 0 represents a path and 1 represents a wall.
     */
    public int[][] getMaze() {
        return maze;
    }

    /**
     * sets the start position of the maze.
     *
     * @param startPosition The position where the maze starts.
     */
    public void setStartPosition(Position startPosition) {
        this.startPosition = startPosition;
    }

    /**
     * returns the start position of the maze.
     *
     * @return The starting position.
     */
    public Position getStartPosition() {
        return startPosition;
    }

    /**
     * sets the end (goal) position of the maze.
     *
     * @param goalPosition The position where the maze ends.
     */
    public void setGoalPosition(Position goalPosition) {
        this.goalPosition = goalPosition;
    }

    /**
     * returns the end (goal) position of the maze.
     *
     * @return The goal position.
     */
    public Position getGoalPosition() {
        return goalPosition;
    }

    /**
     * prints a visual representation of the maze.
     * 'S' indicates the start position, 'E' the goal, '0' a path, and '1' a wall.
     */
    public void print() {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < rows; i++) {
            for (int j = 0; j < columns; j++) {
                // if a start point
                if (new Position(i, j).equals(startPosition)) {
                    sb.append("S");
                }
                // אם מדובר בנקודת סיום
                else if (new Position(i, j).equals(goalPosition)) {
                    sb.append("E");  // End
                }
                // path =0
                else if (maze[i][j] == 0) {
                    sb.append("0");
                }

                // wall =1
                else {
                    sb.append("1");
                }
            }
            sb.append("\n");
        }
        System.out.println(sb.toString());
    }


}
